// End-to-end walkthrough of the core loop. Screenshots each step (QA) and can record video (demo).
import { chromium } from '@playwright/test';
const out = process.argv[2] ?? 'walk';
const base = process.env.BASE ?? 'http://localhost:4173/';
const W = Number(process.env.W ?? 1500), H = Number(process.env.H ?? 1000);
const browser = await chromium.launch({ executablePath: process.env.CHROME });
const ctx = await browser.newContext({ viewport: { width: W, height: H }, ignoreHTTPSErrors: true, ...(process.env.VIDEO ? { recordVideo: { dir: out, size: { width: W, height: H } } } : {}) });
const page = await ctx.newPage();
page.on('pageerror', (e) => console.log('PAGEERROR', e.message));
let n = 0;
const shot = async (name) => { await page.screenshot({ path: `${out}/${String(++n).padStart(2, '0')}-${name}.png` }); console.log('shot', name); };
const wait = (ms) => page.waitForTimeout(ms);
await page.goto(base);
await page.evaluate(() => localStorage.clear());
await page.goto(base + '#/');
await wait(1500);
await shot('map');
await page.goto(base + '#/stream/trois-ponts');
await wait(1200); await shot('stream-before');
await page.click('text=Take the pulse');
await wait(800); await shot('safety');
await page.click("text=I'm on the bank");
await wait(500);
await page.click('.samples button >> nth=0');
await wait(1500); await shot('photo');
await page.click('button:has-text("Continue")');
const picks = ['Cloudy, with whitish deposits', 'Thick foam that stays', 'A faint unusual smell', 'Very slow', 'Natural and stable', 'Dense, with trees and bushes', 'None'];
for (const p of picks) { await wait(500); if (p === picks[1]) await shot('question'); await page.click(`.choice:has-text("${p}")`); }
await wait(700); await shot('context');
await page.click('text=Review my check-up');
await wait(600); await shot('seal-before');
await page.click('text=I confirm my check-up');
await wait(900); await shot('sealed');
await wait(2200); await shot('reveal');
for (const b of await page.$$('button:has-text("I keep my answer")')) await b.click();
await wait(400); await shot('decided');
await page.click('text=Add my check-up to the chart');
await wait(1500); await shot('effect');
await page.click('text=See the chart');
await wait(1500); await shot('stream-after');
await page.goto(base + '#/inbox'); await wait(1200); await shot('inbox');
// ecologist signs the Marcaissonne plan
await page.selectOption('.persona select', 'ecologist');
await page.goto(base + '#/stream/marcaissonne'); await wait(1000);
await page.evaluate(() => document.querySelector('.main').scrollTo(0, 560)); await wait(500);
await shot('plan-proposed');
await page.click('.planline >> nth=1 >> button:has-text("Remove")').catch(() => {});
await page.click('text=I validate this plan'); await page.evaluate(() => document.querySelector('.main').scrollTo(0, 560));
await wait(1500); await shot('plan-signed');
await page.selectOption('.persona select', 'technician');
await page.goto(base + '#/ward'); await wait(1000); await shot('ward');
await ctx.close();
await browser.close();
